BMS/urls.py
from django.conf.urls import url
from django.contrib import admin
from APP01 import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # 登录模块
    url(r'^sign_in/', views.sign_in, name='sign_in'),

    # 注销模块
    url(r'^sing_out/', views.sing_out, name='sign_out'),

    # 注册模块
    url(r'^register_name_ajax/', views.register_name_ajax, name='register_name_ajax'),  # ajax检验用户名是否被占用分模块
    # ajax检验第一次与第二次输入的密码是否一致
    url(r'^register_password_ajax/', views.register_password_ajax, name='register_password_ajax'),
    url(r'^register/', views.register, name='register'),  # 注册主体模块


    # 预留登录测试链接界面
    url(r'^cs/', views.cs, name='cs'),
    # url(r'^cs2/', views.cs2, name='cs2'),

    # 图书管理模块
    url(r'^book_dashboard/', views.book_dashboard, name='book_dashboard'),  # 图书管理模块
    url(r'^add_books/', views.add_books, name='add_books'),  # 添加图书模块
    url(r'^del_books/(?P<did>[\d]+)', views.del_books, name='del_books'),  # 删除图书模块
    url(r'^edit_books/(?P<did>[\d]+)', views.edit_books, name='edit_books'),   # 修改图书模块

    # 出版社管理模块
    url(r'^press_dashboard/', views.press_dashboard, name='press_dashboard'),  # 出版社管理模块
    url(r'^add_press/', views.add_press, name='add_press'),  # 添加出版社模块
    url(r'^del_press/(?P<did>[\d]+)', views.del_press, name='del_press'),  # 删除出版社模块
    url(r'^edit_press/(?P<did>[\d]+)', views.edit_press, name='edit_press'),  # 修改出版社模块

    # 作者管理模块
    url(r'^author_dashboard', views.author_dashboard, name='author_dashboard'),  # 作者管理模块
    url(r'^add_author', views.add_author, name='add_author'),  # 添加作者模块
    url(r'^del_author/(?P<did>[\d]+)', views.del_author, name='del_author'),  # 删除作者模块
    url(r'^edit_author/(?P<did>[\d]+)', views.edit_author, name='edit_author'),  # 修改作者模块

    # 默认界面
    url(r'', views.sign_in, name='sign_in'),
]

APP01/models.py
from django.db import models

# Create your models here.


# 书表
class Books(models.Model):
    # 书表id
    id = models.AutoField(primary_key=True)
    # 书名
    title = models.CharField(max_length=32)
    # 出版日期
    date_pub = models.DateField()
    # 书与出版社的关系
    the_press = models.ForeignKey('Press')


# 出版社表
class Press(models.Model):
    # 出版社id
    id = models.AutoField(primary_key=True)
    # 出版商
    publisher = models.CharField(max_length=32)
    # 出版商地址
    address = models.CharField(max_length=50)


# 作者表
class Author(models.Model):
    # 出版社id
    id = models.AutoField(primary_key=True)
    # 作者名
    name = models.CharField(max_length=20)
    # 作者生日
    birthday = models.DateField()
    # 出版过的书
    books_es = models.ManyToManyField(to='Books')


# 登录人员信息表
class User(models.Model):
    # 用户id
    id = models.AutoField(primary_key=True)
    # 用户账号名
    username = models.CharField(max_length=12)
    # 用户登录密码
    password = models.CharField(max_length=24)


# 解释：
    # 出版社与书为：一对多关系，
    # 作者与书为多对多关系。

templates/add_author.html
<!--
创建时间 : 2018/03/31
版本号 : V1
文档名 : add_author.html
编辑人 : he_wm
作 用 : 图书管理-添加作者模块
源存储位置 : D:\pycharm\python\BMS\templates\add_author.html
代码添加及修改说明:
    1、2018/04/03 : 修改了form表单action的提交方式
-->

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>添加作者</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/title-log.ico' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3-3-7/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-3-3-7/js/bootstrap.min.js' %}"></script>
</head>
<body>
<div class="container">
    <div class="col-md-12">
        {% include 'base/nav_menu.html' %}
    </div>
    <div class="col-md-12" style="margin-top: 200px">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">作者信息</h3>
            </div>
            <div class="panel-body">
                {#加载信息 开始#}
                <form class="form-horizontal" action="{% url 'add_author' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="input_name" class="col-sm-2 control-label">姓名</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="input_name" name="author_name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_data" class="col-sm-2 control-label">出生日期</label>
                        <div class="col-sm-6">
                            <input type="date" class="form-control" id="input_data" name="author_date">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-6 col-sm-2 text-right">
                            <input type="submit" class="btn btn-default" value="提交">
                        </div>
                    </div>
                </form>
                {#加载信息 结束#}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/add_books.html
<!--
创建时间 : 2018/03/31
版本号 : V2
文档名 : add_books.html
编辑人 : he_wm
作 用 : 图书管理-添加图书模块
源存储位置 : D:\pycharm\python\BMS\templates\add_books.html
代码添加及修改说明:
    1、2018/04/03 : 修改了form表单action的提交方式
-->

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>添加图书</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/title-log.ico' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3-3-7/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-3-3-7/js/bootstrap.min.js' %}"></script>
</head>
<body>
<div class="container">
<div class="col-md-12">
        {% include 'base/nav_menu.html' %}
    </div>
    <div class="col-md-12" style="margin-top: 200px">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">图书信息</h3>
            </div>
            <div class="panel-body">
                {#加载信息 开始#}
                <form class="form-horizontal" action="{% url 'add_books' %}" method="post">
                {% csrf_token %}
                    <div class="form-group">
                        <label for="input_name" class="col-sm-2 control-label">书名</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="input_name" name="book_name">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_aut" class="col-sm-2 control-label">作者</label>
                        <div class="col-sm-6">
                            <lable>

                                {#显示所有作者方法 开始#}
                                <select name="book_aut" multiple>
                                    {% for aut_l in aut_list %}
                                        <option value="{{ aut_l.id }}">{{ aut_l.name }}</option>
                                    {% endfor %}
                                </select>
                                {#显示所有作者方法 结束#}

                            </lable>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_data" class="col-sm-2 control-label">出版日期</label>
                        <div class="col-sm-6">
                            <input type="date" class="form-control" id="input_data" name="book_date" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_press" class="col-sm-2 control-label">出版社</label>
                        <div>
                            <select id="input_press" class="col-sm-6 btn btn-default" name="book_press"
                                    style="margin-left: 5px">
                                {#显示所有出版社方法 开始#}
                                {% for press_l in press_list %}
                                    <option value="{{ press_l.id }}">{{ press_l.publisher }}</option>
                                {% endfor %}
                                {# 显示所有出版社方法 结束#}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-6 col-sm-2 text-right">
                            <input type="submit" class="btn btn-default" value="提交">
                        </div>
                    </div>
                </form>
                {#加载信息 结束#}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/add_press.html
<!--
创建时间 : 2018/03/31
版本号 : V2
文档名 : add_press.html
编辑人 : he_wm
作 用 : 图书管理-添加出版社模块
源存储位置 : D:\pycharm\python\BMS\templates\add_press.html
代码添加及修改说明:
    1、2018/04/03 : 修改了form表单action的提交方式
-->

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>添加出版社</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/title-log.ico' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3-3-7/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-3-3-7/js/bootstrap.min.js' %}"></script>
</head>
<body>
<div class="container">
    <div class="col-md-12">
        {% include 'base/nav_menu.html' %}
    </div>
    <div class="col-md-12" style="margin-top: 200px">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">出版社信息</h3>
            </div>
            <div class="panel-body">
                {#加载信息 开始#}
                <form class="form-horizontal" action="{% url 'add_press' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="input_name" class="col-sm-2 control-label">出版社名</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="input_name" name="press_name">
                        </div>
                    </div>
                   <div class="form-group">
                        <label for="input_address" class="col-sm-2 control-label">出版社地址</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="input_address" name="press_address">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-6 col-sm-2 text-right">
                            <input type="submit" class="btn btn-default" value="提交">
                        </div>
                    </div>
                </form>
                {#加载信息 结束#}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/author_dashboard.html
<!--
创建时间 : 2018/03/31
版本号 : V2
文档名 : author_dashboard.html
编辑人 : he_wm
作 用 : 图书管理-作者管理主控制模块
源存储位置 : D:\pycharm\python\BMS\templates\author_dashboard.html
代码添加及修改说明:
    1、2018/04/03 : 修改了a标签href的链接方法
-->

{% extends 'base/base.html' %}
{% block countent %}
    <h1 class="page-header">图书管理系统
        <small>作者</small>
    </h1>
    <!--面板开始-->
    <div class="panel panel-primary">
        <div class="panel-heading">
            作者管理
        </div>
        <div class="panel-body">
            <div class="row my-table-toolbar">
                <div class="col-md-3">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">Go!</button>
                                </span>
                    </div><!-- /input-group -->
                </div>
                <div class="col-md-3 pull-right text-right">
                    <a href="{% url 'add_author' %}" class="btn btn-success" data-toggle="modal">新页面添加</a>
                    <a href="" class="btn btn-success" data-toggle="modal" data-target="#my-Modal">添加</a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="bs-example" data-example-id="striped-table">
                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>序号</th>
                                <th>数据库ID</th>
                                <th>作者</th>
                                <th>作者生辰</th>
                                <th>著作图书</th>
                                <th class="text-center">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for i in author_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ i.id }}</td>
                                    <td>{{ i.name }}</td>
                                    <td>{{ i.birthday|date:'Y-m-d' }}</td>
                                    {#显示著作图书方法 开始#}
                                    <td>
                                        {% for book in i.books_es.all %}
                                            {{ book.title }}
                                        {% endfor %}
                                    </td>
                                    {#显示著作图书方法 结束#}
                                    <td class="text-center">
                                        <a href="{% url 'edit_author' i.id %}" class="btn btn-success">编辑</a>
                                        <a href="{% url 'del_author' i.id %}" class="btn btn-danger">删除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="bs-example" data-example-id="disabled-active-pagination">
                <nav aria-label="..." class="text-right">
                    <ul class="pagination">
                        <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">«</span></a>
                        </li>
                        <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <!--面板body结束-->
    </div>
    <!--面板结束-->
{% endblock %}

{% block author %}
    active
{% endblock %}

templates/book_dashboard.html
<!--
创建时间 : 2018/03/31
版本号 : V2
文档名 : book_dashboard.html
编辑人 : he_wm
作 用 : 图书管理-图书管理主控制模块
源存储位置 : D:\pycharm\python\BMS\templates\book_dashboard.html
代码添加及修改说明:
    1、2018/04/03 : 修改了所有a标签的链接方式
-->
{% extends 'base/base.html' %}
{% block countent %}
    <h1 class="page-header">图书管理系统
        <small>图书</small>
    </h1>
    <!--面板开始-->
    <div class="panel panel-primary">
        <div class="panel-heading">
            图书管理
        </div>
        <div class="panel-body">
            <div class="row my-table-toolbar">
                <div class="col-md-3">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for...">
                        <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">Go!</button>
                                </span>
                    </div><!-- /input-group -->
                </div>
                <div class="col-md-3 pull-right text-right">
                    <a href="{% url 'add_books' %}" class="btn btn-success" data-toggle="modal">新页面添加</a>
                    <a href="" class="btn btn-success" data-toggle="modal" data-target="#my-Modal">添加</a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="bs-example" data-example-id="striped-table">
                        <table class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>序号</th>
                                <th>数据库ID</th>
                                <th>书名</th>
                                <th>作者</th>
                                <th>出版日期</th>
                                <th>出版社</th>
                                <th class="text-center">操作</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for i in book_list %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ i.id }}</td>
                                    <td>{{ i.title }}</td>
                                    {#显示图书作者方法 开始#}
                                    <td>
                                        {% for aut in i.author_set.all %}
                                            {{ aut.name }}
                                        {% endfor %}
                                    </td>
                                    {#显示图书作者方法 结束#}

                                    {#显示出版日期方法 开始#}
                                    <td>{{ i.date_pub|date:'Y-m-d' }}</td>
                                    {#显示出版日期方法 结束#}

                                    <td>{{ i.the_press.publisher }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'edit_books' i.id %}" class="btn btn-success">编辑</a>
                                        <a href="{% url 'del_books' i.id %}" class="btn btn-danger">删除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="bs-example" data-example-id="disabled-active-pagination">
                <nav aria-label="..." class="text-right">
                    <ul class="pagination">
                        <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">«</span></a>
                        </li>
                        <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
                    </ul>
                </nav>
            </div>
        </div>
        <!--面板body结束-->
    </div>
    <!--面板结束-->
{% endblock %}

{% block books %}
    active
{% endblock %}

templates/cs.html
<!--
创建时间 : 2018/03/31
版本号 : V2
文档名 : cs.html
编辑人 : he_wm
作 用 : 测试链接模块
源存储位置 : D:\pycharm\python\BMS\templates\cs.html
代码添加及修改说明:
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>cs</title>
</head>
<body>
<h1>测试成功</h1>
<form action="{% url 'cs2' %}" method="get">
    <input type="text" id="i1" name="i1" value="{{ i1 }}"> +
    <input type="text" id="i2" name="i2" value="{{ i2 }}"> =
    <input type="text" id="ret" name="ret" value="{{ ret }}">
    <input id="b1" type="button" value="发送AJAX请求">
    <input type="submit" value="submit提交">
</form>
<script src="/static/js/jquery-3.3.1.min.js"></script>
<script>
    $('#b1').on('click', function () {
{#        点击b1标签做的事情#}
        var i1 = $('#i1').val();
        var i2 = $('#i2').val();
{#        把两个数发送到后端相加#}
        $.ajax({
            url:'{% url 'cs' %}',
            type:'GET',
            data:{'i1':i1,'i2':i2},
            success:function (arg) {
                $('#ret').val(arg)
            }
        })
    })
</script>

</body>
</html>

templates/edit_author.html
<!--
创建时间 : 2018/03/31
版本号 : V2
文档名 : edit_author.html
编辑人 : he_wm
作 用 : 图书管理系统-修改作者模块
源存储位置 : D:\pycharm\python\BMS\templates\edit_author.html
代码添加及修改说明:
    1、2018/04/03 : 修改了form表单提交方式 action=
-->

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>修改作者</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/title-log.ico' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3-3-7/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-3-3-7/js/bootstrap.min.js' %}"></script>
</head>
<body>
<div class="container">
    <div class="col-md-12">
        {% include 'base/nav_menu.html' %}
    </div>
    <div class="col-md-12" style="margin-top: 200px">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">作者信息</h3>
            </div>
            <div class="panel-body">
                {#加载信息 开始#}
                <form class="form-horizontal" action="{% url 'edit_author' author_list.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group" hidden>
                        <label for="input_id" class="col-sm-2 control-label">作者id</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="input_id" name="author_id"
                                   value="{{ author_list.id }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_name" class="col-sm-2 control-label">姓名</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="input_name" name="author_name"
                                   value="{{ author_list.name }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_data" class="col-sm-2 control-label">出生日期</label>
                        <div class="col-sm-6">
                            <input type="date" class="form-control" id="input_data" name="author_date"
                                   value="{{ author_list.birthday|date:'Y-m-d' }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-6 col-sm-2 text-right">
                            <input type="submit" class="btn btn-default" value="提交">
                        </div>
                    </div>
                </form>
                {#加载信息 结束#}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/edit_books.html
<!--
创建时间 : 2018/03/31
版本号 : V2
文档名 : edit_books
编辑人 : he_wm
作 用 : 图书管理系统-修改图书模块
源存储位置 : D:\pycharm\python\BMS\templates\edit_books.html
代码添加及修改说明:
    1、2018/04/03 : 修改了form表单提交方式 action="/edit_books/1/
    2、2018/04/03 : 修改了form表单提交方式 action=
-->

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>编辑图书</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/title-log.ico' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3-3-7/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-3-3-7/js/bootstrap.min.js' %}"></script>
</head>
<body>
<div class="container">
<div class="col-md-12">
        {% include 'base/nav_menu.html' %}
    </div>
    <div class="col-md-12" style="margin-top: 200px">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">图书信息</h3>
            </div>
            <div class="panel-body">
                {#加载信息 开始#}
                <form class="form-horizontal" action="{% url 'edit_books' book_list.id %}" method="post">
                {% csrf_token %}
                    <div class="form-group" hidden>
                        <label for="input_id" class="col-sm-2 control-label">图书id</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="input_id" name="book_id"
                                   value="{{ book_list.id }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_name" class="col-sm-2 control-label">书名</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="input_name" name="book_name"
                                   value="{{ book_list.title }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_aut" class="col-sm-2 control-label">作者</label>
                        <div class="col-sm-6">
                            {#显示作者 开始#}
                            <lable>
                                <select name="book_aut" multiple>
                                    {% for aut_l in aut_list %}
                                        {% if aut_l in book_list.author_set.all %}
                                            <option selected value="{{ aut_l.id }}">{{ aut_l.name }}</option>
                                        {% else %}
                                            <option value="{{ aut_l.id }}">{{ aut_l.name }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </lable>
                            {#显示作者 结束#}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_data" class="col-sm-2 control-label">出版日期</label>
                        <div class="col-sm-6">
                            <input type="date" class="form-control" id="input_data" name="book_date"
                                   value="{{ book_list.date_pub|date:'Y-m-d' }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_press" class="col-sm-2 control-label">出版社</label>
                        <div>
                            <select id="input_press" class="col-sm-6 btn btn-default" name="book_press"
                                    style="margin-left: 5px">
                                {#此处为显示图书出版商的方法-期中判断的用处为出版此书的出版商产生选定状态#}
                                {% for press_l in press_list %}
                                    {% if press_l in book_list.the_press %}
                                        <option selected value="{{ press_l.id }}">{{ press_l.publisher }}</option>
                                    {% else %}
                                        <option value="{{ press_l.id }}">{{ press_l.publisher }}</option>
                                    {% endif %}
                                {% endfor %}
                                {#结束显示出版商方法#}
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-6 col-sm-2 text-right">
                            <input type="submit" class="btn btn-default" value="提交">
                        </div>
                    </div>
                </form>
                {#加载信息 结束#}
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/edit_press.html
<!--
创建时间 : 2018/03/31
版本号 : V2
文档名 : edit_press
编辑人 : he_wm
作 用 : 图书管理系统-修改出版社模块
源存储位置 : D:\pycharm\python\BMS\templates\edit_press.html
修改及增加功能记录 :
    1、2018/04/03 : 修改了form表单提交数据方式action
-->

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>编辑出版社</title>
    {% load static %}
    <link rel="icon" href="{% static 'img/title-log.ico' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-3-3-7/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'bootstrap-3-3-7/js/bootstrap.min.js' %}"></script>
</head>
<body>
<div class="container">
    <div class="col-md-12">
        {% include 'base/nav_menu.html' %}
    </div>
    <div class="col-md-12" style="margin-top: 200px">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">出版社信息</h3>
            </div>
            <div class="panel-body">
                {#加载信息开始#}
                <form class="form-horizontal" action="{% url 'edit_press' press_list.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group" hidden>
                        <label for="input_id" class="col-sm-2 control-label">出版社id</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="input_id" name="press_id" value="{{ press_list.id }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="input_name" class="col-sm-2 control-label">出版社名</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="input_name" name="press_name" value="{{ press_list.publisher }}">
                        </div>
                    </div>
                   <div class="form-group">
                        <label for="input_address" class="col-sm-2 control-label">出版社地址</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="input_address" name="press_address" value="{{ press_list.address }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-6 col-sm-2 text-right">
                            <input type="submit" class="btn btn-default" value="提交">
                        </div>
                    </div>
                </form>
                {#加载信息结束#}
            </div>
        </div>
    </div>
</div>
</body>
</html>